# Generated by Django 5.0.7 on 2024-10-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaTicket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="validate_code",
            field=models.CharField(default="57d22d", max_length=6),
        ),
    ]
