# Generated by Django 5.0.7 on 2024-08-03 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaTicket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projection_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("created_at", models.DateField(default=datetime.date.today)),
                ("cinema_room", models.ManyToManyField(to="cinemaTicket.cinemaroom")),
            ],
        ),
    ]
