# Generated by Django 5.0.7 on 2024-09-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaTicket", "0002_remove_projection_cinema_rooms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp_code", models.CharField(max_length=6)),
                ("otp_created_at", models.DateTimeField(auto_now_add=True)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
