# Generated by Django 5.0.7 on 2024-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaTicket", "0004_movie_projection_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projection",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="projection",
            name="projection_date",
            field=models.DateTimeField(),
        ),
    ]
